[package]
name = "lib3h_sim_chat"
version = "0.0.10"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2018"
description = "lib3h simulation test framework"
keywords = ["holochain", "holo"]
categories = ["development-tools::testing"]
license = "Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/lib3h_sim_chat"
repository = "https://github.com/holochain/lib3h"

[dependencies]
crossbeam-channel = "=0.3.8"
linefeed = "=0.6.0"
base64 = "=0.10.1"
regex = "=1.1.2"
lib3h_protocol = { "path" = "../../lib3h_protocol" }
lib3h_sodium = { "path" = "../../sodium" }
lib3h_crypto_api = { "path" = "../../crypto_api" }
lib3h = { "path" = "../../lib3h" }
lib3h_ghost_actor = { "path" = "../../ghost_actor" }
lib3h_tracing = { "path" = "../../tracing" }
detach = { "path" = "../../detach" }
url = "=1.7.2"
lazy_static = "=1.2.0"
serde = "=1.0.89"
serde_derive = "=1.0.89"
serde_json = "=1.0.39"
chrono = "=0.4.6"

[lib]
name = "lib3h_sim_chat"
path = "src/lib.rs"

[[bin]]
name = "lib3h_sim_chat"
path = "src/main.rs"
