[workspace]

members = [
  "crates/logging",
  "crates/crypto_api",
  "crates/sodium",
  "crates/lib3h_protocol",
  "crates/p2p_protocol",
  "crates/lib3h",
  "crates/tools/half_busy_chat",
  "crates/tools/capnp_build",
]
