[package]
name = "holochain_lib3h_protocol"
version = "0.0.1-alpha1"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2018"

[dependencies]
holochain_logging = { path = "../logging" }
failure = "=0.1.5"
