version: 2

jobs:
 build:
  docker:
   - image: holochain/holonix:latest
  steps:
   - checkout
   - run: nix-shell --run l3h-test
 macos:
  macos:
   xcode: "10.2.0"
  steps:
   - checkout
   - run:
      name: tests via nix
      command: |
       curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
       MAKE_ENV=local make

workflows:
 version: 2
 tests:
  jobs:
   - build
   - macos
