[package]
name = "lib3h"
version = "0.0.3-alpha1"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2018"
# crates.io stuff
description = "The lib3h p2p communication rust library."
keywords = ["holochain", "holo", "p2p", "network"]
categories = ["network-programming"]
license = "Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/lib3h"
repository = "https://github.com/holochain/lib3h"

[dependencies]
hcid = "=0.0.6"
holochain_persistence_api = "=0.0.4-alpha1"
lib3h_protocol = { path = "../lib3h_protocol", version = "=0.0.3-alpha1" }
lib3h_crypto_api = { path = "../crypto_api", version = "=0.0.3-alpha1" }
tungstenite = "=0.6.1"
url = "=1.7.2"
url_serde = "=0.2.0"
native-tls = "=0.2.2"
rmp-serde = "=0.13.7"
serde = "=1.0.89"
serde_derive = "=1.0.89"
failure = "=0.1.5"
log = "=0.4.6"
# Should be dev only
lazy_static = "=1.2.0"

[dev-dependencies]
unwrap_to = "=0.1.0"
backtrace = "=0.3.14"
env_logger = "=0.6.1"
bincode = "=1.1.4"
multihash = "=0.8.0"
